### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by bohdandonets** [Vitalii13Kotelianets/My-movie-rating-project#1]
якась хуйня забагована, ну йобаний в рот, дядьку блять

**Comment by Vitalii13Kotelianets** [comment]
@bohdandonets в чому баг? Поясни дядьку. Може то фіча така

**Comment by bohdandonets** [comment]
та я їбав пояснювати) та думаю і так норм, можна в прод)

**Comment by Vitalii13Kotelianets** [comment]
@bohdandonets fixed.
